### ISSUE TITLE
qq音乐部分纯音乐接口获取歌词返回错误码400

### ISSUE THREAD

**Issue by happy888liu** [mrdong916/mess-api-doc#2]
https://v1.itooi.cn/tencent/lrc?id=001Dzt1m4bxFSN
这个是获取失败的链接，获取结果为：
{code: 400,msg: "获取数据失败",timestamp: 1559238550136}
其他纯音乐歌词获取结果为：
https://v1.itooi.cn/tencent/lrc?id=002URiHF2KamxI
[00:00:00]此歌曲为没有填词的纯音乐，请您欣赏

**Comment by mrdong916** [comment]
由于这首音乐QQ音乐官方接口返回的是错误信息导致

**Comment by happy888liu** [comment]
那么接口是否可以统一输出结果为 [00:00:00]暂无歌词
